# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15248b273633eb5243eca15c1c09fcac3702bab9dabe845285d6036dd356e26209d447fd05d44bf24f6b02f0c76aae95d91e9de7185c9d79c98f7bb4627de7c8

test:
  secret_key_base: 333a6b3582341e65c2c2545a05745b8e4b33f64820eedceb72146c222fa92fb422a7882867d45edc864e40fc4c597ad23c8b1315cc0af08d2943a79124b309da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
